- hosts: web
  sudo: yes
  vars:
    PROJECT_HOME: "/opt/error-log-parser-v2"
  tasks:
  - name: Install package git python pip
    yum: name={{item}} state=installed update_cache=true
    with_items:
        - git
        - python
        - python-pip
  - name: Get Error Paser v2
    git: repo=https://github.com/lusa-hust/error-log-parser-v2.git
         dest=/opt/error-log-parser-v2
  - name: Install virtualenv
    pip: name=virtualenv
  - name: Create virtualenv
    shell: virtualenv "{{ PROJECT_HOME }}/env"
           creates="{{ PROJECT_HOME }}/env/bin/activate"
  - name: Install requirements
    pip: requirements="/opt/error-log-parser-v2/requirements.txt" 
         virtualenv="/opt/error-log-parser-v2/env"